# Generated by Django 3.1.4 on 2021-02-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowYourself', '0003_auto_20210208_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodypartsdetection',
            name='image',
            field=models.ImageField(upload_to='knowYourself'),
        ),
    ]
