# Generated by Django 3.1.4 on 2021-02-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowYourself', '0004_auto_20210208_0625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.AlterField(
            model_name='bodypartsdetection',
            name='action',
            field=models.CharField(choices=[('nose', 'nose'), ('frontalFace', 'frontalFace'), ('eye', 'eye'), ('mouth', 'mouth')], default=None, max_length=11),
        ),
        migrations.AlterField(
            model_name='bodypartsdetection',
            name='image',
            field=models.ImageField(upload_to='media/knowYourself'),
        ),
    ]
