# Generated by Django 3.1.4 on 2021-02-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowYourself', '0005_auto_20210208_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodypartsdetection',
            name='action',
        ),
    ]
