# Generated by Django 3.1.4 on 2021-02-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowYourself', '0007_auto_20210208_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodypartdetection',
            name='image',
            field=models.ImageField(upload_to='knowYourself/imageDB/'),
        ),
    ]
